# Generated by Django 2.0.2 on 2018-02-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teammates', '0001_initial'),
        ('teemizone', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('desired_tech', models.ManyToManyField(blank=True, to='teemizone.TechSkill')),
                ('requrements', models.ManyToManyField(blank=True, help_text='Select the Desired Pofession', to='teemizone.Profession')),
                ('selected_team', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='selected_team', to='teammates.Team')),
                ('team_candidates', models.ManyToManyField(blank=True, related_name='team_candidates', to='teammates.Team')),
                ('tools', models.ManyToManyField(blank=True, to='teemizone.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
