# Generated by Django 2.0 on 2018-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teemizone', '0002_auto_20180125_0746'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='desired_tech',
        ),
        migrations.AddField(
            model_name='project',
            name='desired_tech',
            field=models.ManyToManyField(to='teemizone.TechSkill'),
        ),
    ]
