# Generated by Django 2.0 on 2018-01-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0002_auto_20180126_2109'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_candidates',
            field=models.ManyToManyField(blank=True, related_name='team_candidates', to='teammates.Team'),
        ),
    ]
