# Generated by Django 2.0 on 2018-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180125_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='excludes',
        ),
        migrations.AlterField(
            model_name='project',
            name='requrements',
            field=models.ManyToManyField(help_text='Select the Desired Pofession', to='teemizone.Profession'),
        ),
    ]
