# Generated by Django 2.0 on 2018-01-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0002_auto_20180126_2109'),
        ('projects', '0002_project_team_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_team',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selected_team', to='teammates.Team'),
            preserve_default=False,
        ),
    ]
