# Generated by Django 2.0 on 2018-01-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180125_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desired_tech',
            field=models.ManyToManyField(blank=True, to='teemizone.TechSkill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requrements',
            field=models.ManyToManyField(blank=True, help_text='Select the Desired Pofession', to='teemizone.Profession'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='teemizone.Tool'),
        ),
    ]
