# Generated by Django 2.0 on 2018-01-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180129_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='selected_team',
        ),
    ]
