# Generated by Django 2.0 on 2018-01-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_selected_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='selected_team',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='selected_team', to='teammates.Team'),
        ),
    ]
