# Generated by Django 2.0 on 2018-01-26 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teemizone', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_profession', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teemizone.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Student'), ('G', 'Graduate'), ('J', 'Junior'), ('I', 'Intermediate'), ('P', 'Professional'), ('M', 'Mixed')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='teammates.Member')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='teemizone.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequiredProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('accepted_teammate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to=settings.AUTH_USER_MODEL)),
                ('candidates', models.ManyToManyField(blank=True, related_name='candidates', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
                ('profession', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teemizone.Profession')),
                ('responsibilities', models.ManyToManyField(blank=True, to='teammates.Responsibilities')),
                ('tags', models.ManyToManyField(blank=True, to='teemizone.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, choices=[('0', 'No Experience'), ('1', '0-1 Years'), ('2', '1-3 Years'), ('3', '3-5 Years'), ('4', 'More THan 5 Years')], max_length=100)),
                ('technologies', models.ManyToManyField(blank=True, to='teemizone.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='teamrequiredprofession',
            name='what_we_need',
            field=models.ManyToManyField(blank=True, to='teammates.WhatWeNeed'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_jobs',
            field=models.ManyToManyField(to='teammates.TeamRequiredProfession'),
        ),
    ]
