# Generated by Django 2.0 on 2018-01-25 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teemizone', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teammate_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
                ('teammate_profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='TeemateJobEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=100)),
                ('job_duration', models.CharField(max_length=100)),
                ('job_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
            ],
        ),
        migrations.AddField(
            model_name='teammate',
            name='teemate_jobs_hostory',
            field=models.ManyToManyField(to='teammates.TeemateJobEntity'),
        ),
    ]
