# Generated by Django 2.0 on 2018-01-25 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teemizone', '0003_auto_20180125_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teammates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teemizone.Industry')),
            ],
        ),
        migrations.RenameField(
            model_name='teematejobentity',
            old_name='job_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='teematejobentity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammate',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teematejobentity',
            name='job_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
